
// This file has been generated by the GUI designer. Do not modify.
public partial class MainWindow
{
	private global::Gtk.VBox vbox1;
	private global::Gtk.HBox hbox1;
	private global::Gtk.CheckButton ckbxCamera;
	private global::Gtk.ComboBox cbxCamera;
	private global::Gtk.Button btnRec;
	private global::Gtk.HBox hbox3;
	private global::Gtk.CheckButton ckbxDisplay;
	private global::Gtk.Entry txtScreen;
	private global::Gtk.Label lblStatus;
	private global::Gtk.HBox hbox2;
	private global::Gtk.CheckButton ckbxMic;
	private global::Gtk.ComboBox cbxMic;
	private global::Gtk.Button btnPause;
	private global::Gtk.HBox hbox4;
	private global::Gtk.Label lblFolder;
	private global::Gtk.Entry txtFolderOut;
	private global::Gtk.Button btnFolder;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox1 = new global::Gtk.VBox ();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 6;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox1 = new global::Gtk.HBox ();
		this.hbox1.Name = "hbox1";
		this.hbox1.Spacing = 6;
		// Container child hbox1.Gtk.Box+BoxChild
		this.ckbxCamera = new global::Gtk.CheckButton ();
		this.ckbxCamera.CanFocus = true;
		this.ckbxCamera.Name = "ckbxCamera";
		this.ckbxCamera.Label = global::Mono.Unix.Catalog.GetString ("Camera");
		this.ckbxCamera.DrawIndicator = true;
		this.ckbxCamera.UseUnderline = true;
		this.hbox1.Add (this.ckbxCamera);
		global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.ckbxCamera]));
		w1.Position = 0;
		// Container child hbox1.Gtk.Box+BoxChild
		this.cbxCamera = global::Gtk.ComboBox.NewText ();
		this.cbxCamera.Name = "cbxCamera";
		this.hbox1.Add (this.cbxCamera);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.cbxCamera]));
		w2.Position = 1;
		w2.Expand = false;
		w2.Fill = false;
		// Container child hbox1.Gtk.Box+BoxChild
		this.btnRec = new global::Gtk.Button ();
		this.btnRec.CanFocus = true;
		this.btnRec.Name = "btnRec";
		this.btnRec.UseUnderline = true;
		this.btnRec.Label = global::Mono.Unix.Catalog.GetString ("Rec");
		this.hbox1.Add (this.btnRec);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.btnRec]));
		w3.Position = 2;
		w3.Expand = false;
		w3.Fill = false;
		this.vbox1.Add (this.hbox1);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox1]));
		w4.Position = 0;
		w4.Expand = false;
		w4.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox3 = new global::Gtk.HBox ();
		this.hbox3.Name = "hbox3";
		this.hbox3.Spacing = 6;
		// Container child hbox3.Gtk.Box+BoxChild
		this.ckbxDisplay = new global::Gtk.CheckButton ();
		this.ckbxDisplay.CanFocus = true;
		this.ckbxDisplay.Name = "ckbxDisplay";
		this.ckbxDisplay.Label = global::Mono.Unix.Catalog.GetString ("Display");
		this.ckbxDisplay.DrawIndicator = true;
		this.ckbxDisplay.UseUnderline = true;
		this.hbox3.Add (this.ckbxDisplay);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.ckbxDisplay]));
		w5.Position = 0;
		// Container child hbox3.Gtk.Box+BoxChild
		this.txtScreen = new global::Gtk.Entry ();
		this.txtScreen.CanFocus = true;
		this.txtScreen.Name = "txtScreen";
		this.txtScreen.IsEditable = true;
		this.txtScreen.InvisibleChar = '●';
		this.hbox3.Add (this.txtScreen);
		global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.txtScreen]));
		w6.Position = 1;
		// Container child hbox3.Gtk.Box+BoxChild
		this.lblStatus = new global::Gtk.Label ();
		this.lblStatus.Name = "lblStatus";
		this.lblStatus.LabelProp = global::Mono.Unix.Catalog.GetString ("status");
		this.hbox3.Add (this.lblStatus);
		global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.lblStatus]));
		w7.Position = 2;
		w7.Expand = false;
		w7.Fill = false;
		this.vbox1.Add (this.hbox3);
		global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox3]));
		w8.Position = 1;
		w8.Expand = false;
		w8.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox2 = new global::Gtk.HBox ();
		this.hbox2.Name = "hbox2";
		this.hbox2.Spacing = 6;
		// Container child hbox2.Gtk.Box+BoxChild
		this.ckbxMic = new global::Gtk.CheckButton ();
		this.ckbxMic.CanFocus = true;
		this.ckbxMic.Name = "ckbxMic";
		this.ckbxMic.Label = global::Mono.Unix.Catalog.GetString ("Microphone");
		this.ckbxMic.DrawIndicator = true;
		this.ckbxMic.UseUnderline = true;
		this.hbox2.Add (this.ckbxMic);
		global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.ckbxMic]));
		w9.Position = 0;
		// Container child hbox2.Gtk.Box+BoxChild
		this.cbxMic = global::Gtk.ComboBox.NewText ();
		this.cbxMic.Name = "cbxMic";
		this.hbox2.Add (this.cbxMic);
		global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.cbxMic]));
		w10.Position = 1;
		w10.Expand = false;
		w10.Fill = false;
		// Container child hbox2.Gtk.Box+BoxChild
		this.btnPause = new global::Gtk.Button ();
		this.btnPause.CanFocus = true;
		this.btnPause.Name = "btnPause";
		this.btnPause.UseUnderline = true;
		this.btnPause.Label = global::Mono.Unix.Catalog.GetString ("Pause");
		this.hbox2.Add (this.btnPause);
		global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.btnPause]));
		w11.Position = 2;
		w11.Expand = false;
		w11.Fill = false;
		this.vbox1.Add (this.hbox2);
		global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox2]));
		w12.Position = 2;
		w12.Expand = false;
		w12.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox4 = new global::Gtk.HBox ();
		this.hbox4.Name = "hbox4";
		this.hbox4.Spacing = 6;
		// Container child hbox4.Gtk.Box+BoxChild
		this.lblFolder = new global::Gtk.Label ();
		this.lblFolder.Name = "lblFolder";
		this.lblFolder.LabelProp = global::Mono.Unix.Catalog.GetString ("Каталог");
		this.hbox4.Add (this.lblFolder);
		global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.lblFolder]));
		w13.Position = 0;
		w13.Expand = false;
		w13.Fill = false;
		// Container child hbox4.Gtk.Box+BoxChild
		this.txtFolderOut = new global::Gtk.Entry ();
		this.txtFolderOut.CanFocus = true;
		this.txtFolderOut.Name = "txtFolderOut";
		this.txtFolderOut.IsEditable = true;
		this.txtFolderOut.InvisibleChar = '●';
		this.hbox4.Add (this.txtFolderOut);
		global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.txtFolderOut]));
		w14.Position = 1;
		// Container child hbox4.Gtk.Box+BoxChild
		this.btnFolder = new global::Gtk.Button ();
		this.btnFolder.CanFocus = true;
		this.btnFolder.Name = "btnFolder";
		this.btnFolder.UseUnderline = true;
		this.btnFolder.Label = global::Mono.Unix.Catalog.GetString ("...");
		this.hbox4.Add (this.btnFolder);
		global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.btnFolder]));
		w15.Position = 2;
		w15.Expand = false;
		w15.Fill = false;
		this.vbox1.Add (this.hbox4);
		global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox4]));
		w16.PackType = ((global::Gtk.PackType)(1));
		w16.Position = 3;
		w16.Expand = false;
		w16.Fill = false;
		this.Add (this.vbox1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 400;
		this.DefaultHeight = 244;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.btnRec.Clicked += new global::System.EventHandler (this.btnRec_Clicked);
		this.btnPause.Clicked += new global::System.EventHandler (this.btnPause_Clicked);
		this.btnFolder.Clicked += new global::System.EventHandler (this.btnFolderOut_Click);
	}
}
